export const sitcomData = {
    "Friends": {
        "Happy": [
            { "title": "The One with the Embryos", "season": 4, "episode": 12, "specific_reason": "The trivia game bet represents the peak of the group's dynamic. Watching the high-energy competition will instantly boost your adrenaline and mood." },
            { "title": "The One Where No One's Ready", "season": 3, "episode": 2, "specific_reason": "A bottle episode of pure chaos. Joey wearing all of Chandler's clothes is a visual gag that never fails to induce belly laughter." },
            { "title": "The One with the Cop", "season": 5, "episode": 16, "specific_reason": "PIVOT! The physical comedy of moving the couch is legendary and will distract you from any gloom with sheer absurdity." },
            { "title": "The One with the Prom Video", "season": 2, "episode": 14, "specific_reason": "A wholesome classic. The 'He's her lobster' moment provides a warm, fuzzy feeling that combats negativity." },
            { "title": "The One Where Everybody Finds Out", "season": 5, "episode": 14, "specific_reason": "The psychological warfare between Phoebe, Rachel, and Chandler is hysterical and satisfyingly clever." },
            { "title": "The One with the Rumor", "season": 8, "episode": 9, "specific_reason": "Brad Pitt's cameo and the 'I Hate Rachel Green Club' adds a layer of meta-humor that is delightfully entertaining." },
            { "title": "The One with Unagi", "season": 6, "episode": 17, "specific_reason": "Ross's pretentiousness backfiring is always a treat. 'Salmon Skin Roll' will be stuck in your head, replacing negative thoughts." },
            { "title": "The One with the Football", "season": 3, "episode": 9, "specific_reason": "The Geller Cup rivalry is pure sibling energy. It’s competitive, petty, and hilariously relatable fun." },
            { "title": "The One Where Ross Got High", "season": 6, "episode": 9, "specific_reason": "Jack and Judy Geller are roasting masters. The rapid-fire confessions at the end are a dopamine hit." },
            { "title": "The One with the Blackout", "season": 1, "episode": 7, "specific_reason": "Chandler stuck in a vestibule with a model. It’s classic awkward humor that makes you feel better about your own social skills." },
            { "title": "The One with All the Resolutions", "season": 5, "episode": 11, "specific_reason": "Ross in leather pants. The powder change paste situational comedy is slapstick gold." },
            { "title": "The One with the Jellyfish", "season": 4, "episode": 1, "specific_reason": "The lengths they go to for each other (even the gross stuff) proves their bond. Plus, 'WE WERE ON A BREAK!'" },
            { "title": "The One Where Eddie Won't Go", "season": 2, "episode": 19, "specific_reason": "Eddie is arguably the funniest side character. His descent into madness makes the main cast seem sane and grounding." },
            { "title": "The One with Chandler in a Box", "season": 4, "episode": 8, "specific_reason": "Proof that friendship survives anything. It’s funny, touching, and silent comedy from Matthew Perry." },
            { "title": "The One with the Proposal", "season": 6, "episode": 25, "specific_reason": "A double-dose of happiness. Seeing Chandler finally grow up and get what he wants is the ultimate mood lifter." }
        ],
        "Sad": [
            { "title": "The One Where Old Yeller Dies", "season": 2, "episode": 20, "specific_reason": "Phoebe learning the truth about sad movies is a gentle way to process sadness through humor." },
            { "title": "The One with the List", "season": 2, "episode": 8, "specific_reason": "It validates that making mistakes in love is normal. Ross's screw-up is painful but human." },
            { "title": "The One Where Mr. Heckles Dies", "season": 2, "episode": 3, "specific_reason": "Chandler identifying with the lonely neighbor allows you to confront fears of loneliness in a safe, fictional space." },
            { "title": "The One with the Morning After", "season": 3, "episode": 16, "specific_reason": "Sometimes you need to cry it out. The raw acting from Aniston and Schwimmer provides a necessary emotional release." },
            { "title": "The Last One", "season": 10, "episode": 17, "specific_reason": "Endings are hard, but this one is closure. It reminds you that every chapter ends so a new one can begin." },
            { "title": "The One with the Sonogram at the End", "season": 1, "episode": 2, "specific_reason": "Ross grappling with the complexity of life shows that even in messy situations, things work out." },
            { "title": "The One with the Invitation", "season": 4, "episode": 21, "specific_reason": "Looking back at Ross and Rachel's history is nostalgic and bittersweet, perfect for a melancholy mood." },
            { "title": "The One Where Rosita Dies", "season": 7, "episode": 13, "specific_reason": "A lighter take on loss (of a chair). It balances the feeling of sadness with ridiculous stakes." },
            { "title": "The One with the Monkey", "season": 1, "episode": 10, "specific_reason": "The pact to not bring dates to New Year's is a comfort for anyone feeling lonely during the holidays." },
            { "title": "The One Where Nana Dies Twice", "season": 1, "episode": 8, "specific_reason": "Explores grief with a heavy dose of absurdity. Shows that laughter is often the best coping mechanism during tragedy." },
            { "title": "The One with All the Thanksgivings", "season": 5, "episode": 8, "specific_reason": "Flashbacks show everyone considers their worst days. It puts your current sadness into perspective: at least you aren't without a toe." },
            { "title": "The One Without the Ski Trip", "season": 3, "episode": 17, "specific_reason": "Dealing with the fallout of the breakup. It's validating to see a friend group struggle and then reconcile." },
            { "title": "The One with the Fertility Test", "season": 9, "episode": 21, "specific_reason": "Monica and Chandler's struggle is handled with grace. It says it's okay for things not to go to plan." },
            { "title": "The One Where They're Up All Night", "season": 7, "episode": 12, "specific_reason": "Insomnia and restlessness. It keeps you company when you feel like the only person awake with your thoughts." },
            { "title": "The One with the Cake", "season": 10, "episode": 4, "specific_reason": "Even the best plans fail. A reminder to just laugh when things go wrong instead of despairing." }
        ],
        "Broken": [
            { "title": "The One with the Prom Video", "season": 2, "episode": 14, "specific_reason": "When you feel unlovable, this episode proves that someone out there has loved you all along." },
            { "title": "The One with the Proposal (Part 2)", "season": 6, "episode": 25, "specific_reason": "If you've had your heart broken, watching two people fight for their love restores faith in romance." },
            { "title": "The One Hundredth", "season": 5, "episode": 3, "specific_reason": "Phoebe giving up the triplets. It teaches the beauty of selfless love and doing the right thing even when it hurts." },
            { "title": "The One Where Ross and Rachel... You Know", "season": 2, "episode": 15, "specific_reason": "The culmination of longing. It’s a reminder that the wait is often worth it." },
            { "title": "The One with the Truth About London", "season": 7, "episode": 16, "specific_reason": "Fate works in mysterious ways. Monica and Chandler were meant to be, proving broken paths can lead to the right destination." },
            { "title": "The One with Barry and Mindy's Wedding", "season": 2, "episode": 24, "specific_reason": "Rachel facing her past mistakes and realizing she made the right choice helps when you're doubting your life path." },
            { "title": "The One with the Jellyfish", "season": 4, "episode": 1, "specific_reason": "Reconciliation is possible. It might be messy, but wounds can heal." },
            { "title": "The One Where Rachel Finds Out", "season": 1, "episode": 24, "specific_reason": "The realization of love. It’s that spark of hope you need when you feel emotionally dead." },
            { "title": "The One with All the Wedding Dresses", "season": 4, "episode": 20, "specific_reason": "Sometimes you just need to sit in a wedding dress and drink beer. It validates your need to wallow before moving on." },
            { "title": "The One with the Blind Dates", "season": 9, "episode": 14, "specific_reason": "Rock bottom proves you can survive the worst and the only way is up." },
            { "title": "The One After 'I Do'", "season": 8, "episode": 1, "specific_reason": "Rachel's pregnancy fear. It shows that life-altering news can be the start of something beautiful, not just a breakage." },
            { "title": "The One Where Chandler Can't Cry", "season": 6, "episode": 14, "specific_reason": "If you feel numb, this validates that everyone processes emotions differently." },
            { "title": "The One with the Ring", "season": 6, "episode": 23, "specific_reason": "Chandler's determination to fix his mistake shows that if something is broken, you can fight to fix it." },
            { "title": "The One with Phobe's Wedding", "season": 10, "episode": 12, "specific_reason": "Phoebe, the one with the hardest life, gets her happy ending. Absolute proof that you are not too broken for happiness." },
            { "title": "The One Where They Say Goodbye", "season": 10, "episode": 18, "specific_reason": "Saying goodbye is the ultimate heartbreak, but this shows that love endures beyond physical proximity." }
        ],
        "Stressed": [
            { "title": "The One Where No One's Ready", "season": 3, "episode": 2, "specific_reason": "The real-time format mirrors your anxiety but filters it through comedy. Watching them spiral makes your stress feel silly." },
            { "title": "The One with the Embryos", "season": 4, "episode": 12, "specific_reason": "The rapid-fire questions demand your full attention, forcing your brain to dump its background processes and stress." },
            { "title": "The One Where Ross is Fine", "season": 10, "episode": 2, "specific_reason": "Ross's manic energy is the perfect caricature of stress. Laughing at his 'I'm Fine' helps you admit you aren't, which is relaxing." },
            { "title": "The One with All the Rugby", "season": 4, "episode": 15, "specific_reason": "Physical, brutal, and chaotic. Sometimes you need to see people run into each other to release tension." },
            { "title": "The One with the Unagi", "season": 6, "episode": 17, "specific_reason": "The jump scares will jolt your nervous system, resetting your stress baseline." },
            { "title": "The One where They Don't Know We Know", "season": 5, "episode": 14, "specific_reason": "The layers of secrets are a mental puzzle. Solving it with them takes focus off your own stressors." },
            { "title": "The One with the Lottery", "season": 9, "episode": 18, "specific_reason": "The collective hope and subsequent disappointment is a low-stakes way to process anxiety about the future." },
            { "title": "The One with the Apothecary Table", "season": 6, "episode": 11, "specific_reason": "Phoebe's hatred of Pottery Barn is a trivial problem that allows you to escape real-world heavy issues." },
            { "title": "The One with the Ride-Along", "season": 5, "episode": 20, "specific_reason": "A car backfire treated as a gunshot. It’s a hilarious overreaction that mocks the high-stakes nature of stress." },
            { "title": "The One with the Late Thanksgiving", "season": 10, "episode": 8, "specific_reason": "Everyone is late and stressed. It validates your feeling of being overwhelmed but wraps it in warmth." },
            { "title": "The One with the Cat", "season": 4, "episode": 2, "specific_reason": "Phoebe believing a cat is her mom is so absurd it breaks the cycle of logical, stressful thinking." },
            { "title": "The One with the Pivot", "season": 5, "episode": 16, "specific_reason": "The frustration of moving furniture is relatable stress turned into comedy gold." },
            { "title": "The One with the Nap Partners", "season": 7, "episode": 6, "specific_reason": "Watching people nap is oddly soothing. It subliminally gives you permission to rest." },
            { "title": "The One with the Videotape", "season": 8, "episode": 4, "specific_reason": "A mystery where the details matter. It engages your analytical brain on something fun rather than stressful work." },
            { "title": "The One with the Routine", "season": 6, "episode": 10, "specific_reason": "Monica and Ross's desperate need for perfection mirrors your stress but makes it look ridiculous." }
        ]
    },
    "How I Met Your Mother": {
        "Happy": [
             { "title": "Slap Bet", "season": 2, "episode": 9, "specific_reason": "The discovery of Robin Sparkles is pure joy. 'Let's Go To The Mall' is an earworm that forces a smile." },
             { "title": "The Pineapple Incident", "season": 1, "episode": 10, "specific_reason": "A hang-over mystery that is harmless fun. The lack of real consequences makes it a light, happy watch." },
             { "title": "Swarley", "season": 2, "episode": 7, "specific_reason": "The gang's commitment to a gag is infectious. You'll feel like part of the inside joke." },
             { "title": "Girls Versus Suits", "season": 5, "episode": 12, "specific_reason": "A full-blown musical number about suits. It’s high-energy spectacle that boosts endorphins." },
             { "title": "The Playbook", "season": 5, "episode": 8, "specific_reason": "Barney's schemes are morally questionable but undeniably creative and hilarious to watch unfold." },
             { "title": "Spoiler Alert", "season": 3, "episode": 8, "specific_reason": "Realizing your friends' flaws are annoying is handled with love. It turns irritation into comedy." },
             { "title": "Three Days of Snow", "season": 4, "episode": 13, "specific_reason": "The airport marching band scene is one of the most heartwarming, triumphant moments in the series." },
             { "title": "Subway Wars", "season": 6, "episode": 4, "specific_reason": "A love letter to New York and competition. The fast pace keeps your energy high." },
             { "title": "Ten Sessions", "season": 3, "episode": 13, "specific_reason": "Current Ted’s two-minute date is a masterclass in romance and efficiency. Optimism at its finest." },
             { "title": "The Naked Man", "season": 4, "episode": 9, "specific_reason": "A risky move that works 2 out of 3 times. It’s audacious, funny, and surprisingly hopeful." },
             { "title": "Lucky Penny", "season": 2, "episode": 15, "specific_reason": "Tracing a chain of events shows how small happy accidents shape our lives." },
             { "title": "The Best Burger in New York", "season": 4, "episode": 2, "specific_reason": "The quest for food is the most relatable joy. Watching Marshall eat that burger is vicarious satisfaction." },
             { "title": "Intervention", "season": 4, "episode": 4, "specific_reason": "The recurring joke of the banner is funny, and it shows a group that cares enough to stop you from being an idiot." },
             { "title": "Wooo!", "season": 4, "episode": 8, "specific_reason": "Sometimes the best way to be happy is to just let go and go 'WOOO!'. A permission slip for silliness." },
             { "title": "Glitter", "season": 6, "episode": 9, "specific_reason": "More Robin Sparkles (and Jessica Glitter). The space show song is absurdly catchy and lighthearted." }
        ],
        "Sad": [
             { "title": "Bad News", "season": 6, "episode": 13, "specific_reason": "The countdown to Marshall's dad's death. It allows you to grieve and process shock in a safe environment." },
             { "title": "Last Words", "season": 6, "episode": 14, "specific_reason": "Dealing with the aftermath of loss. It validates the desire for one more conversation with a loved one." },
             { "title": "Tick Tick Tick", "season": 7, "episode": 10, "specific_reason": "Barney cleaning up the rose petals alone is a heart-wrenching image of unrequited hope." },
             { "title": "Symphony of Illumination", "season": 7, "episode": 12, "specific_reason": "Robin finding out she can't have kids. It handles a heavy topic with a beautiful, metaphorical ending." },
             { "title": "The Time Travelers", "season": 8, "episode": 20, "specific_reason": "The ending monologue about running to the person you love is devastatingly beautiful and lonely." },
             { "title": "How Your Mother Met Me", "season": 9, "episode": 16, "specific_reason": "Tracy's side of the story. Her loss of Max mirrors Ted's loneliness, making you feel understood." },
             { "title": "Vesuvius", "season": 9, "episode": 19, "specific_reason": "Ted realizing his mother is dying. It’s a preemptive mourning that hits deep if you fear losing someone." },
             { "title": "Legendaddy", "season": 6, "episode": 19, "specific_reason": "Barney realizing Jerry is just a lame suburban dad. The 'Why couldn't you be that for me?' line is cathartic." },
             { "title": "Doppelgangers", "season": 5, "episode": 24, "specific_reason": "Lily and Marshall's silent struggle with fertility. It captures the quiet sadness of waiting." },
             { "title": "Come On", "season": 1, "episode": 22, "specific_reason": "Ted making it rain while Marshall sits in the rain with the ring. The contrast of hope and heartbreak is poignant." },
             { "title": "Something Blue", "season": 2, "episode": 22, "specific_reason": "Ted and Robin's breakup. It shows that sometimes love isn't enough, which is a sad but necessary truth." },
             { "title": "Cleaning House", "season": 6, "episode": 2, "specific_reason": "Barney's mom trying to protect him from the truth. A touching look at parental love and sacrifice." },
             { "title": "Definitions", "season": 5, "episode": 1, "specific_reason": "The fear of defining a relationship. It captures the modern sadness of 'situationships'." },
             { "title": "The Final Page (Part 2)", "season": 8, "episode": 12, "specific_reason": "It’s a happy moment for Barney, but Ted letting go is a supreme act of sad selflessness." },
             { "title": "Last Forever", "season": 9, "episode": 24, "specific_reason": "The controversial finale. It deals with the reality that life moves on, friends drift, and things end." }
        ],
        "Broken": [
             { "title": "Drumroll, Please", "season": 1, "episode": 13, "specific_reason": "Ted meets Victoria. It proves that magical connections exist, helping you believe in love again." },
             { "title": "Shelter Island", "season": 4, "episode": 5, "specific_reason": "Being left at the altar (almost). It shows that dodging a bullet hurts, but saves you from a fatal wound." },
             { "title": "No Pressure", "season": 7, "episode": 17, "specific_reason": "Ted declaring his love for Robin again. It validates the feeling of being stuck on someone." },
             { "title": "Bachelor Party", "season": 2, "episode": 19, "specific_reason": "Marshall realizing Lily left for SF. It hits the feeling of betrayal, but finding solace in friends." },
             { "title": "Benefits", "season": 4, "episode": 12, "specific_reason": "Trying to fix a broken heart with casual flings. It shows why that doesn't work, which is a good reality check." },
             { "title": "The Leap", "season": 4, "episode": 24, "specific_reason": "The metaphor of the leap. Sometimes you just have to jump to the next roof to fix your life." },
             { "title": "Challenge Accepted", "season": 6, "episode": 24, "specific_reason": "Ted seeing Zoey and fearing he's back at square one. It’s about the exhaustion of trying." },
             { "title": "Milk", "season": 1, "episode": 21, "specific_reason": "Ted realizing the 'perfect' woman isn't the *right* woman. Helps if you feel you missed a chance." },
             { "title": "Nothing Good Happens After 2 A.M.", "season": 1, "episode": 18, "specific_reason": "We all make mistakes when we are lonely. This helps you forgive yourself for late-night texts." },
             { "title": "Robots Versus Wrestlers", "season": 5, "episode": 22, "specific_reason": "Feeling drifted from your friends. It validates the fear of growing apart." },
             { "title": "Arrivederci, Fiero", "season": 2, "episode": 17, "specific_reason": "Saying goodbye to a car representing your youth. It’s about letting go of the past." },
             { "title": "Happily Ever After", "season": 4, "episode": 6, "specific_reason": "Stella in the car. It’s about not letting your baggage define your future." },
             { "title": "Unfinish", "season": 6, "episode": 3, "specific_reason": "Ted deciding to finish the GNB tower. It’s about rebuilding your dreams after they've been crushed." },
             { "title": "Right Place, Right Time", "season": 4, "episode": 22, "specific_reason": "If you feel broken by bad luck, this reminds you the universe might be positioning you for something better." },
             { "title": "Farhampton", "season": 8, "episode": 1, "specific_reason": "Klaus's speech about the 'Lebenslangerschicksalsschatz'. It gives you a word for the feeling you are missing." }
        ],
        "Stressed": [
             { "title": "The Wedding Bride", "season": 5, "episode": 23, "specific_reason": "Ted seeing his trauma turned into a cheesy movie. It shows that eventually, your stress will be a funny story." },
             { "title": "The Burning Beekeeper", "season": 7, "episode": 15, "specific_reason": "A chaotic dinner party told room by room. The structure keeps your brain busy, distracting from stress." },
             { "title": "Game Night", "season": 1, "episode": 15, "specific_reason": "Uncovering everyone's embarrassing pasts. It reminds you that everyone has secrets and insecurities." },
             { "title": "Sweet Taste of Liberty", "season": 1, "episode": 3, "specific_reason": "Barney's mission to lick the Liberty Bell is so low-stakes and stupid it relieves pressure." },
             { "title": "Arrivederci, Fiero", "season": 2, "episode": 17, "specific_reason": "Marshall's car struggles are relatable frustrations (potholes, breakdowns) played for laughs." },
             { "title": "Wait for It", "season": 3, "episode": 1, "specific_reason": "Enrique Iglesias as 'Gael'. The sheer awkwardness of Robin's cool boyfriend makes your problems seem small." },
             { "title": "Little Minnesota", "season": 4, "episode": 11, "specific_reason": "Marshall finding his people. A reminder that there’s a comfort zone for everyone." },
             { "title": "Jenkins", "season": 5, "episode": 13, "specific_reason": "Marshall trying to hide a female coworker from jealousy. It’s a farce that mocks unnecessary stress." },
             { "title": "Zoo or False", "season": 5, "episode": 19, "specific_reason": "The monkey mugging story changes every time. It proves memory is unreliable, so stop stressing about details." },
             { "title": "The Bracket", "season": 3, "episode": 14, "specific_reason": "Searching for the woman sabotaging Barney. It’s a mystery format that engages the mind." },
             { "title": "Home Wreckers", "season": 5, "episode": 20, "specific_reason": "Ted impulsively buys a house. It shows that making a huge stressful decision can sometimes be right." },
             { "title": "Disaster Averted", "season": 7, "episode": 9, "specific_reason": "Hurricane Irene. Being trapped with friends turns a stressful event into a bonding memory." },
             { "title": "Trilogy Time", "season": 7, "episode": 20, "specific_reason": "Watching Star Wars every 3 years. The routine and predictability are soothing for a stressed mind." },
             { "title": "Stuff", "season": 2, "episode": 16, "specific_reason": "Fighting over exes' stuff. It mocks the material attachments that cause us stress." },
             { "title": "Murtaugh", "season": 4, "episode": 19, "specific_reason": "The 'I'm too old for this' list. Relatable acceptance of your limits which reduces FOMO stress." }
        ]
    },
    "The Big Bang Theory": {
        "Happy": [
            { "title": "The Bath Item Gift Hypothesis", "season": 2, "episode": 11, "specific_reason": "Sheldon hugging Penny is pure, undiluted joy. A 'Saturnalia miracle' that guarantees a smile." },
            { "title": "The adhesive Duck Deficiency", "season": 3, "episode": 8, "specific_reason": "'Soft Kitty' sung in a round. The physical comedy of Penny injured and Sheldon driving is peak sitcom." },
            { "title": "The Stark Trek Transmogrification", "season": 12, "episode": 22, "specific_reason": "A D&D game that heals relationships. It shows the power of play to fix real-world mood." },
            { "title": "The Scavenger Vortex", "season": 7, "episode": 3, "specific_reason": "The group splits into unusual pairs for a hunt. Highly energetic, competitive, and fun." },
            { "title": "The Pants Alternative", "season": 3, "episode": 18, "specific_reason": "Drunk Sheldon accepting an award. His lack of inhibition is freeing and hilarious." },
            { "title": "The Opening Night Excitation", "season": 9, "episode": 11, "specific_reason": "Sheldon choosing Amy over Star Wars. A colossal moment of romantic happiness." },
            { "title": "The Proposal Proposal", "season": 11, "episode": 1, "specific_reason": "Amy saying yes purely because she assumes it's rhetorical. It’s sweet, funny, and triumphant." },
            { "title": "The Hawkituncular Excitation", "season": 6, "episode": 21, "specific_reason": "Sheldon meeting Stephen Hawking. Seeing a hero meet their hero is vicariously thrilling." },
            { "title": "The Stockholm Syndrome", "season": 12, "episode": 24, "specific_reason": "The Finale. Sheldon's speech acknowledging his friends is the perfect happy tear-jerker." },
            { "title": "The 43 Peculiarity", "season": 6, "episode": 8, "specific_reason": "Howard and Raj finding Sheldon's wormhole. The mystery is engaging and the payoff is funny." },
            { "title": "The Love Car Displacement", "season": 4, "episode": 13, "specific_reason": "Everyone at a hotel convention. The room switching farce is fast-paced fun." },
            { "title": "The Celebration Reverberation", "season": 11, "episode": 11, "specific_reason": "Halley's birthday is a disaster, but the group bonding over it is heartwarming." },
            { "title": "The Convention Conundrum", "season": 7, "episode": 14, "specific_reason": "James Earl Jones and Carrie Fisher! The celebrity antics are unpredictable and delightful." },
            { "title": "The Indecision Amalgamation", "season": 7, "episode": 19, "specific_reason": "Sheldon struggling between PS4 and Xbox One. The low stakes make it a relaxing, happy watch." },
            { "title": "The Werewolf Transformation", "season": 5, "episode": 18, "specific_reason": "Sheldon playing bongos. 'Penny meant playing!' It’s chaotic good energy." }
        ],
        "Sad": [
            { "title": "The Santa Simulation", "season": 6, "episode": 11, "specific_reason": "Sheldon shares his hatred of Christmas. A rare vulnerable moment about his grandfather." },
            { "title": "The Comic Book Store Regeneration", "season": 8, "episode": 15, "specific_reason": "Mrs. Wolowitz's death. The toast to her is a genuine moment of grief and love." },
            { "title": "The Proton Transmogrification", "season": 7, "episode": 22, "specific_reason": "Professor Proton dies. Sheldon hugging Leonard is a huge step in processing loss." },
            { "title": "The Long Distance Dissonance", "season": 10, "episode": 24, "specific_reason": "The cliffhanger where Sheldon proposes. It sits in that anxious space between hope and fear." },
            { "title": "The Commitment Determination", "season": 8, "episode": 24, "specific_reason": "Amy breaking up with Sheldon. Seeing the ring he had brings a heavy dose of regret and sadness." },
            { "title": "The Bon Voyage Reaction", "season": 6, "episode": 24, "specific_reason": "Leonard leaving for the sea. The goodbyes are sincere and touch on the sadness of separation." },
            { "title": "The Stag Convergence", "season": 5, "episode": 22, "specific_reason": "Howard's past sexual history revealed. It’s uncomfortable and sad to see mistakes haunt the present." },
            { "title": "The Closure Alternative", "season": 6, "episode": 21, "specific_reason": "Sheldon's need for closure. It resonates if you’re feeling unresolved about something in your life." },
            { "title": "The Status Quo Combustion", "season": 7, "episode": 24, "specific_reason": "Sheldon getting on a train to leave. The feeling of the world changing too fast is very relatable." },
            { "title": "The Earworm Reverberation", "season": 9, "episode": 10, "specific_reason": "Sheldon realizing the song is about Amy. It captures the subconscious sadness of missing someone." },
            { "title": "The Wildebeest Implementation", "season": 4, "episode": 22, "specific_reason": "Bernadette and Priya double dating. Seeing Penny feel replaced is a sharp, relatable pain." },
            { "title": "The Speckerman Recurrence", "season": 5, "episode": 11, "specific_reason": "Leonard confronting his bully. The realization that the bully hasn't changed is a sad reality check." },
            { "title": "The Countdown Reflection", "season": 5, "episode": 24, "specific_reason": "Howard going to space. The fear of leaving Earth and loved ones is palpable." },
            { "title": "The Thanksgiving Decoupling", "season": 7, "episode": 9, "specific_reason": "Penny realizes she married Zack. The sadness of realizing you made a huge mistake years ago." },
            { "title": "The Intimacy Acceleration", "season": 8, "episode": 16, "specific_reason": "Sheldon and Penny doing the eye-contact experiment. It’s surprisingly intimate and reveals hidden vulnerabilities." }
        ],
        "Broken": [
            { "title": "The Recombination Hypothesis", "season": 5, "episode": 13, "specific_reason": "The 100th episode 'what if'. It shows that even if you feel broken, you can eventually try again." },
            { "title": "The Tangible Affection Proof", "season": 6, "episode": 16, "specific_reason": "Raj's loneliness party. It speaks to the feeling of being the only single/broken one in a group." },
            { "title": "The Separation Triangulation", "season": 10, "episode": 14, "specific_reason": "Raj being cut off financially. It’s about being broken down to build yourself back up." },
            { "title": "The Spoiler Alert Segmentation", "season": 6, "episode": 15, "specific_reason": "Leonard moving in with Penny, then not. The back and forth of a broken relationship trying to fix itself." },
            { "title": "The Clean Room Infiltration", "season": 8, "episode": 10, "specific_reason": "Raj's dad coming for Christmas. Dealing with broken family dynamics during the holidays." },
            { "title": "The Friendship Contraction", "season": 5, "episode": 15, "specific_reason": "Leonard breaking the roommate agreement. It shows that boundaries are needed to fix broken friendships." },
            { "title": "The Proton Regeneration", "season": 11, "episode": 6, "specific_reason": "Sheldon trying to replace Professor Proton. Coping with the fact that childhood heroes are gone." },
            { "title": "The Application Deterioration", "season": 10, "episode": 18, "specific_reason": "Sheldon, Leonard, Howard patent fight. Money breaks friendships, but this shows how to repair them." },
            { "title": "The Confidence Erosion", "season": 11, "episode": 10, "specific_reason": "Raj and Howard's friendship breakup. Sometimes you have to break a bond to grow as a person." },
            { "title": "The Plagiarism Schism", "season": 12, "episode": 19, "specific_reason": "Amy vs Pemberton/Campbell. The feeling of having your hard work stolen or broken is validated." },
            { "title": "The Decoupling Fluctuation", "season": 5, "episode": 14, "specific_reason": "Penny thinking about breaking up with Leonard. The anxiety of impending heartbreak." },
            { "title": "The Maternal Capacitance", "season": 2, "episode": 15, "specific_reason": "Beverly Hofstadter psychoanalyzing everyone. It exposes everyone's broken pieces." },
            { "title": "The Prestidigitation Approximation", "season": 4, "episode": 18, "specific_reason": "Priya bans Penny from Leonard. The feeling of being excluded and broken from your own circle." },
            { "title": "The First Pitch Insufficiency", "season": 8, "episode": 3, "specific_reason": "Howard's terrible pitch. Failing publically is crushing, but laughing at it heals." },
            { "title": "The Cooper-Nowitzki Theorem", "season": 2, "episode": 6, "specific_reason": "Sheldon being stalked by Ramona. It shows that even 'perfect' admiration can be broken and toxic." }
        ],
        "Stressed": [
            { "title": "The Barbarian Sublimation", "season": 2, "episode": 3, "specific_reason": "Penny addicted to gaming. Watching someone derail their life for a game is great stress relief." },
            { "title": "The Itchy Brain Simulation", "season": 7, "episode": 8, "specific_reason": "Sheldon forcing Leonard to wear an itchy sweater. It visualizes the sensation of nagging stress." },
            { "title": "The Large Hadron Collision", "season": 3, "episode": 15, "specific_reason": "Leonard vs Sheldon for the Swiss conference. The pettiness is a distraction from real-world pressure." },
            { "title": "The Parking Spot Escalation", "season": 6, "episode": 9, "specific_reason": "The feud over the parking spot. It captures how small stressors can blow up, and mocks them." },
            { "title": "The Cruciferous Vegetable Amplification", "season": 4, "episode": 2, "specific_reason": "Sheldon trying to live forever. His stress about health is so exaggerated it makes yours feel manageable." },
            { "title": "The Work Song Nanocluster", "season": 2, "episode": 18, "specific_reason": "Penny Blossoms. The stress of a startup and caffeine addiction is hilarious chaos." },
            { "title": "The Bozeman Reaction", "season": 3, "episode": 13, "specific_reason": "Sheldon moves to Bozeman and gets robbed. It shows running away doesn't fix stress." },
            { "title": "The Habitation Configuration", "season": 6, "episode": 7, "specific_reason": "Sheldon on 'Fun with Flags'. The director stress is low-stakes and funny." },
            { "title": "The Solder Excursion Diversion", "season": 9, "episode": 19, "specific_reason": "Leonard and Howard lying to wives. The stress of maintaining a lie is played for maximum comedy." },
            { "title": "The Veracity Elasticity", "season": 10, "episode": 7, "specific_reason": "Amy lying about her apartment being fixed. The stress of cohabitation is relatable." },
            { "title": "The Staircase Implementation", "season": 3, "episode": 22, "specific_reason": "Flashback to the elevator breaking. Seeing the origin of their daily inconvenience is oddly soothing." },
            { "title": "The Griffin Equivalency", "season": 2, "episode": 4, "specific_reason": "Raj being famous and annoying. The social stress of a friend changing is handled with humor." },
            { "title": "The Euclid Alternative", "season": 2, "episode": 5, "specific_reason": "Sheldon learning to drive. The stress of the simulator is a safe way to experience panic." },
            { "title": "The Terminator Decoupling", "season": 2, "episode": 17, "specific_reason": "Summer Glau on the train. The stress of talking to a celebrity is pure cringe comedy." },
            { "title": "The Precious Fragmentation", "season": 3, "episode": 17, "specific_reason": "Fighting over the One Ring. The nerd rage is high-stress but harmless." }
        ]
    }
};
